version: '3.8'

services: 
  db:
    image: postgis/postgis
    env_file: 
      - .env
    ports:
        - 5432:5432
  web:
      build: .
      env_file: 
        - .env
      command: python /code/manage.py runserver 0.0.0.0:8000
      volumes:
          - .:/code
      ports:
          - 8000:8000
      depends_on: 
          - db
