# Generated by Django 3.2.8 on 2021-10-29 14:47

import datetime
import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('REVIEW', 'Under Review'), ('ACCEPTED', 'Accepted'), ('CLOSED', 'Resolved')], default='NEW', max_length=8)),
                ('geom', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('description', models.TextField()),
                ('date_added', models.DateTimeField(default=datetime.datetime.today)),
            ],
        ),
    ]
