# Generated by Django 3.2.8 on 2021-10-28 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='geometry',
            new_name='geom',
        ),
    ]
